version: '{build}'

image:
  - Visual Studio 2013

configuration:
  - Release

install:
  - git submodule update --init --recursive

build:
  project: Synchronization.sln

artifacts:
  - path: '%CONFIGURATION%\Synchronization.exe'
